import _Signup from "@/components/_signup";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: 'sign up',
    description: 'Generated by create next app',
}

export default function SignupPage() {
    return (
        <div>
            <_Signup/>
        </div>
    )
}