import { Metadata } from "next"


export const metadata: Metadata = {
    title: 'Terms and conditions',
    description: 'Generated by create next app',
}

export default function TermsPage() {
    return (
        <div>
            this is the terms page
        </div>
    )
}