import { Metadata } from "next"


export const metadata: Metadata = {
    title: 'Privacy',
    description: 'Generated by create next app',
}

export default function PrivacyPage() {
    return (
        <div>
            this is the privacy page
        </div>
    )
}