import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'About Afro buy',
    description: 'Generated by create next app',
}


export default function AboutPage() {
    return (
        <div>
            this is the about page
        </div>
    )
}